# Site settings
title: LiXtudio
header-img: img/home-bg.jpg
email: 1569910942@qq.com
copyright_name: LiXtudio
description: "Learning Sharing"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: xlong_us
#weibo_username: weibo
github_username:  lixtudio
facebook_username:  xiaolngli
email_username:  1569910942@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
