# Site settings
title: Leading The Way
header-img: img/home-bg.jpg
email: 1569910942@qq.com
copyright_name: Leading The Way
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
#twitter_username: SBootstrap
weibo_username: weibo
github_username:  leading-theway
#facebook_username:  IronSummitMedia
email_username:  1569910942@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
